# -*- coding: utf-8 -*-
"""Climdes analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NZZ_AHFYp7SSBCQxsabibewjX-vSLWI9
"""

import pandas as pd
import numpy as np
import seaborn as sns
import datetime as dt
import plotly.express as px
from matplotlib import pyplot as plt

df = pd.read_excel("/Sensor.xlsx")
data = df.iloc[1:, :]

data.head()

data.describe()

data.columns

dataA = data[["Date/ Time", "A1. Temp. (°C)", "A1. Humidity (%)"]]
dataA.head()

dataA.describe()

dataA1sample = dataA.sample(frac=0.1, replace=False)
dataA1sample

plt.hist(dataA1sample["A1. Temp. (°C)"])
plt.title("Sensor A1 data distribution in April")
plt.xlabel("Values")
plt.ylabel("Frequency")
plt.show()

plt.hist(dataA1sample["A1. Humidity (%)"])
plt.title("Sensor A1 Humidity data distribution in April")
plt.xlabel("Values")
plt.ylabel("Frequency")
plt.show()